name: my_business_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.3.0
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  image_cropper: ^9.1.0
  path_provider: ^2.1.1
  path: ^1.8.3
  dotted_border: ^2.0.0
  permission_handler: ^11.0.0
  uuid: ^3.0.6
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  google_sign_in: ^6.2.0
  cloud_firestore: ^6.0.0
  camera: ^0.11.2
  video_player: ^2.0.0
  
  
  flutter_localizations:
    sdk: flutter
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/logo.png